### ISSUE TITLE
Ability to list the products by name

### ISSUE THREAD

**Issue by dd3053** [Products-Development-Team/products#50]
**As a** Customer
 **I need** to search for a product by name  
 **So that** I can search for a particular product easily.
   
 ### Details and Assumptions
 * The API's must be RESTful.
 * The base URL is /products.
 * URL should return the list of all the products with a particular name.
 * Add query capability to the model
 * Add query string support to the List function 
 * The`GET` request to `/products?name=<name_string>` will return a collection of products with name as `name_string`.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I know the name of the product I want
 When I send a GET Request to /products?name="shirt"
 Then I get a return a collection of products with name as shirt
 ```

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/50?planning-poker) with ZenHub @dggjsc @hxwang-463 @mpourostad @yuluqinn

**Comment by yuluqinn** [comment]
Hi Devesh, I have a doubt about this name attribute: are we assuming the name attribute is not a unique one but could have multiple duplicates? Like a category attribute? In category we have men/women, for name: we are expecting to have T-shirt, sweater, etc instead of a unique name like RELAXED-FIT PRINTED T-SHIRT or PRINTED SARONG? I just refer to a clothing store website so I am asking: https://www.cos.com/en_usd/collaborations.html What do you guys think? @dd3053 @hxwang-463 @dggjsc @mpourostad

**Comment by dd3053** [comment]
Nice point.

I made this user story with the assumption that product id's are unique however names can be same.
Additionally in the file `factories.py` , `name = FuzzyChoice(choices=["shirt", "sweater", "pants", "lounge_wear"])` made me think that names can be same.
I also need the clarification regarding the `name` property.
