### ISSUE TITLE
Need to create database model and schema

### ISSUE THREAD

**Issue by dggjsc** [Products-Development-Team/products#9]
**As a** User
 **I need** database model and schema to store resources
 **So that** we can implement the functions for products and keep track of updated information

**Details and Assumptions**
* The database should contain product attributes including an id, name, description and price.

**Acceptance Criteria:**
```gherkin
Given the need to maintain/update information about products
When the user add/delete/update something on the website
Then the backend database can respond and update accordingly
 ```

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/9?planning-poker) with ZenHub @dggjsc @mpourostad @xiaokailll @yuluqinn

**Comment by yuluqinn** [comment]
@dggjsc My suggestion for your reference: 
As a User
I need database model and schema to store resources
So that we can keep track of the continuously-updated products information

Details and Assumptions
The database should contain resource attributes including an id, name, description and price. 

Acceptance Criteria: 
Given the need to maintain/update information about the products
When the user add/delete/update something on the website
Then the backend database can respond and update accordingly
